{{- if and .Values.ghcrRegistryAuth.enabled .Values.ghcrRegistryAuth.eso.enabled .Values.ghcrRegistryAuth.eso.createResources }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.ghcrRegistryAuth.eso.clusterSecretStoreName }}
  labels:
    {{- include "glerp-monitoring.labels" . | nindent 4 }}
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ .Values.ghcrRegistryAuth.eso.sourceNamespace }}
      server:
        url: "https://kubernetes.default.svc"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: {{ .Values.ghcrRegistryAuth.eso.controllerNamespace }}
      auth:
        serviceAccount:
          name: {{ .Values.ghcrRegistryAuth.eso.controllerServiceAccount }}
          namespace: {{ .Values.ghcrRegistryAuth.eso.controllerNamespace }}
{{- end }}
